### ISSUE TITLE
bug: Monitor tool - TypeError: Cannot read properties of undefined (reading 'messageHash')

### ISSUE THREAD

**Issue by yourbuddyconner** [celo-org/optics-monorepo#867]
Bridge monitor tool currently doesn't work, need it to work. 

```
/Users/connerswann/code/optics-monorepo/typescript/contract-metrics/src/monitor.ts:4
import config from './config';
           ^
TypeError: Cannot read properties of undefined (reading 'messageHash')
    at /Users/connerswann/code/optics-monorepo/typescript/contract-metrics/src/monitor.ts:81:28
    at Array.map (<anonymous>)
    at /Users/connerswann/code/optics-monorepo/typescript/contract-metrics/src/monitor.ts:80:48
    at Generator.next (<anonymous>)
    at /Users/connerswann/code/optics-monorepo/typescript/contract-metrics/src/monitor.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/connerswann/code/optics-monorepo/typescript/contract-metrics/src/monitor.ts:4:12)
    at writeUnprocessedMessages (/Users/connerswann/code/optics-monorepo/typescript/contract-metrics/src/monitor.ts:68:12)
    at /Users/connerswann/code/optics-monorepo/typescript/contract-metrics/src/monitor.ts:124:9
    at Generator.next (<anonymous>)
```

**Comment by anna-carroll** [comment]
fixed
